# https://travis-ci.org/HearthSim/HearthstoneJSON.com
sudo: false
language: ruby
rvm: "2.4.1"

cache: bundler

script: bundle exec jekyll build

after_success: '[[ $TRAVIS_PULL_REQUEST = "false" && $TRAVIS_BRANCH == "master" ]] && bundle exec s3_website push'

notifications:
  email:
    on_failure: always
    on_success: change

  irc:
    channels:
      - "chat.freenode.net#hearthsim-commits"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
