name: HearthstoneJSON
description: JSON files for Hearthstone
logo: images/logo.png

url: https://hearthstonejson.com

markdown: kramdown

kramdown:
  input: GFM

sass:
  style: :compressed

exclude:
  - CNAME
  - LICENSE
  - README.md
  - vendor/
